/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonCount: typeof import('./src/views/vue3/component/ButtonCount.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Lifecycle: typeof import('./src/components/lifecycle.vue')['default']
    LifecycleChild: typeof import('./src/components/LifecycleChild.vue')['default']
    LifecycleComp: typeof import('./src/components/LifecycleComp.vue')['default']
    LifecycleKeepalive: typeof import('./src/components/LifecycleKeepalive.vue')['default']
    LifecycleParent: typeof import('./src/components/lifecycleParent.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    LoopRenderComp: typeof import('./src/components/LoopRenderComp.vue')['default']
    LoopRenderComponent: typeof import('./src/components/LoopRenderComponent.vue')['default']
    LoopRenderComponentCount: typeof import('./src/components/LoopRenderComponentCount.vue')['default']
    LoopRenderItem: typeof import('./src/components/LoopRenderItem.vue')['default']
    LoopRenderItemCount: typeof import('./src/components/LoopRenderItemCount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateComponent: typeof import('./src/components/StateComponent.vue')['default']
    StaticComponent: typeof import('./src/components/StaticComponent.vue')['default']
  }
}
